= Big Data Infrastructure Exercises

We'll use this repository through our course.
Starting it from a small application to have something
bigger and more complex.

== Installation

* Use python 3.11
* https://github.com/pypa/pipx#install-pipx[Install `pipx` 🔗]
* Install poetry (dependency manager) `pipx install poetry`

Run `poetry install`

If you need to add any package, just add it inside `pyproject.toml`
to the `[tool.poetry.dependencies]` section.
Then run `poetry update`

You may find some other packages need to be pip installed even after running poetry.
pip install uvicorn
pip install fastapi
pip install pydantic-settings
pip install importlib-metadata

== Libraries

https://fastapi.tiangolo.com/[FastAPI] is one of the best libraries for building an API with Python.
It has a great documentation and enables us to build
type safe and documented APIs easily.

== Data
Use the `data/` folder to store your data.
It will not be uploaded to any git repository.

== Run the app on localhost
cd project_code # Move into the folder where app.py is located
uvicorn app:app --reload # Start the application on localhost
